# Generated by Django 4.2.6 on 2023-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_ordercl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercl',
            name='name',
        ),
        migrations.AddField(
            model_name='ordercl',
            name='client_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Введите имя'),
        ),
    ]
